#!/usr/bin/env bash
#This script prints HolbEton School 10 times except for line 9 it says Hi
i=1; while [ $i -le 10 ];
do echo "Holberton School";
if [ $i -eq 9 ];
then echo "Hi";
fi;
	 (( i++ ))
     done
