#!/usr/bin/env bash
# print bad luck on line 4 good luck on lin 8 and holberton on the rest 1-10 loops
lemon=1;
while [ $lemon -le 10 ];
do
  if [ $lemon -eq 4 ];
  then echo "bad luck";
  elif [ $lemon -eq 8 ];
  then echo "good luck";
  else
      echo "Holberton School";
  fi
      (( lemon++ ))
	     done
