#!/usr/bin/env bash
#Script that displays 1-20 4 china 9 japan 17 italy with while and case
lemons=1
while [ $lemons -lt 21 ]
do 
	echo "$lemons"
	
	case "$lemons" in 
		4)
			echo $lemons
		       	echo "bad luck from China"
		;;

		9)
			echo $lemons
		       	echo "bad luck from Japan"
		;;

		17)
			echo $lemons
			echo "bad luck from Italy"
		;;
	esac

	((lemons++))
done
