#!/usr/bin/env bash
#script that displays time for 12 hours nad 59 mins with while
hour=1
while [ "$hour" -le 12 ]
do
        echo "hour: $hour"
        min=1
        while [ "$min" -lt 60 ]

        do
                echo $min
                ((min++))
        done
        ((hour++)) 
done
