#!/usr/bin/env bash
#script that displays time for 12 hours nad 59 mins with while
lemons=1
while [ "$lemons" -le 12 ]
do
        echo "lemons: $lemons"
        limes=1
        while [ "$limes" -lt 60 ]

        do
                echo $limes
                ((limes++))
        done
        ((lemons++)) 
done
